FROM python:3.12


WORKDIR /textgpt-app

COPY requirements_docker.txt .
RUN pip install --no-cache-dir -r requirements_docker.txt


RUN apt-get update && apt-get install -y --no-install-recommends \
    ffmpeg libsm6 libxext6 && \
    apt-get clean && rm -rf /var/lib/apt/lists/*


COPY ./utils ./utils
COPY main.py main.py
COPY ./dbs ./dbs


RUN mkdir -p images
# COPY ./images/gprMax_FB_logo.png ./images/gprMax_FB_logo.png # Not required for now


CMD ["streamlit", "run", "app.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
